x-default-logging: &logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "2"
    tag: "{{.Name}}"

services:
  customers.api:
    build:
      context: .
      dockerfile: ${CUSTOMER_DOCKERFILE}
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5100:5100"
      - "5101:5101"
    networks:
      - bank_network

  transactions.api:
    build:
      context: .
      dockerfile: ${TRANSACTION_DOCKERFILE}
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5200:5200"
      - "5201:5201"
    networks:
      - bank_network
  postgres:
    image: postgres:alpine
    container_name: postgres
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "127.0.0.1:5432:5432" 
    networks:
      - bank_network
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    volumes:
      - pgadmin_working_dir:/var/lib/pgadmin
      - pgadmin_config_dir:/pgadmin4
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      POSTGRES_USER: bankuser
      POSTGRES_PASSWORD: Il0v3kfc@247
    depends_on:
      - postgres
    ports:
      - "5433:80" # HOST_PORT:CONTAINER_PORT
    networks:
      - bank_network

  kafka:
    container_name: kafka
    build:
      context: ./
      dockerfile: ${KAFKA_DOCKERFILE}
      args:
        OTEL_JAVA_AGENT_VERSION: ${OTEL_JAVA_AGENT_VERSION}
    deploy:
      resources:
        limits:
          memory: 620M
    restart: unless-stopped
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${KAFKA_HOST}:9092
      - KAFKA_LISTENERS=PLAINTEXT://${KAFKA_HOST}:9092,CONTROLLER://${KAFKA_HOST}:9093
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@${KAFKA_HOST}:9093
      - KAFKA_HEAP_OPTS=-Xmx400m -Xms400m
      # Workaround on OSX for https://bugs.openjdk.org/browse/JDK-8345296
      - _JAVA_OPTIONS
    healthcheck:
      test: nc -z kafka 9092
      start_period: 10s
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - bank_network
    logging: *logging

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_NAME: "local"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:9092"
    networks:
      - bank_network
  # kafka-init-topics:
  #   image: confluentinc/cp-kafka:7.2.1
  #   volumes:
  #     - ./data/message.json:/data/message.json
  #   networks:
  #     - bank_network
  #   depends_on:
  #     - kafka
  #   command: "bash -c 'echo Waiting for Kafka to be ready... && \
  #     cub kafka-ready -b kafka:9092 1 30 && \
  #     kafka-topics --create --topic bank.transactions --partitions 3 --replication-factor 1 --if-not-exists --bootstrap-server kafka:9092 && \
  #     kafka-topics --create --topic bank.customers --partitions 2 --replication-factor 1 --if-not-exists --bootstrap-server kafka:9092 && \
  #     kafka-topics --create --topic transactions.errors --partitions 2 --replication-factor 1 --if-not-exists --bootstrap-server kafka:90922 && \
  #     kafka-console-producer --bootstrap-server kafka:9092 -topic transactions.topic < /data/message.json'"

volumes:
  db_data:
  pgadmin_working_dir:
    driver: local
  pgadmin_config_dir:
    driver: local

networks:
  bank_network:
    driver: bridge
